USE employee_trackerDB;
DELETE FROM employee_trackerDB.employee;
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id) VALUES ('Giovanni', 'Cordova', '1');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Sue', 'Smith', '2', '1');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('John', 'Black', '10', '1');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Marry', 'Jane', '20', '1');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Jim', 'More', '30', '1');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Miles', 'Clark', '11', '3');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Andre', 'Lee', '12', '3');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Francis', 'Jones', '13', '3');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Kyle', 'Stone', '14', '3');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Kaylee', 'Johnson', '21', '4');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Drew', 'Powers', '22', '4');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Clara', 'Huffman', '23', '4');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Ashley', 'Fin', '31', '5');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Ben', 'Connor', '32', '5');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Sarah', 'Ferrari', '33', '5');
INSERT INTO employee_trackerDB.employee (first_name, last_name, role_id, manager_id) VALUES ('Jill', 'Wilson', '34', '4');
