USE employee_trackerDB;
DELETE FROM role;
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('1', 'CEO', '700000', '1');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('2', 'Vice President', '500000', '1');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('10', 'Senior Develpment Manager', '200000', '3');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('11', 'Developement Manager', '170000', '3');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('12', 'Senior Developer', '150000', '3');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('13', 'Associate Developer', '110000', '3');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('14', 'Intern Developer', '800000', '3');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('20', 'Senior QA Manager', '190000', '4');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('21', 'QA Manager', '160000', '4');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('22', 'Senior Software QA Engineer', '140000', '4');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('23', 'Software QA Engineer', '110000', '4');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('30', 'Senior Design Manager', '200000', '5');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('31', 'Design Manager', '170000', '5');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('32', 'Senior Designer', '150000', '5');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('33', 'Associate Designer', '110000', '5');
INSERT INTO employee_trackerDB.role (id, title, salary, department_id) VALUES ('34', 'Intern Designer', '800000', '5');
